### ISSUE TITLE
Incomplete results

### ISSUE THREAD

**Issue by smwk** [AzureAD/MSAL.PS#21]
Not sure if it's an issue with Graph or the module (I suspect the former) but when I run various reports I get different results returned. An example is this table which shows the amount of Teams in my organization.

![image](https://user-images.githubusercontent.com/20819759/96511294-cb2acf80-1256-11eb-97a3-52390365d5eb.png)

No Teams have been deleted and if I manually check the dashboard all the Teams are still there. The Powershell script does not return an error, it simply completes without returning all the results. I've tried adding a pause between calling the next page, which helped on some scripts, but not this one.

**Comment by jasoth** [comment]
You are correct. This is specific to MS Graph, not MSAL.PS module.

MS Graph uses paging when returning large amounts of data.
https://docs.microsoft.com/en-us/graph/paging

You could look at using the [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) PowerShell modules instead which can handle paging. If you still need to make the underlying REST calls, you could use the `Invoke-RestMethodWithBearerAuth` command I published in the [MSIdentityTools](https://aka.ms/MSIdentityTools) module which has a parameter to automatically return all data from a query.

For Example:
```
Invoke-RestMethodWithBearerAuth -ClientApplication $ClientId -Scopes 'User.Read.All','Group.Read.All' -Method Get -Uri 'https://graph.microsoft.com/v1.0/users' -FollowODataNextLink
```

**Comment by smwk** [comment]
I was actually using paging already, but it seems large queries still cause problems. I'm re-writing my scripts to take this into account.

Thanks for the additional info, will try out Invoke-RestMethodWithBearerAuth.
