### ISSUE TITLE
Get-MsalToken -AzureCloudInstance not working 

### ISSUE THREAD

**Issue by damorris** [AzureAD/MSAL.PS#23]
when using Get-Msaltoken -ClientId XXXXXX -TenantId xxxxxxx -AzureCloudInstance AzureUSGovernment 
a Sign in to your account windows pops up and I pick my account > which goes to taking you to your orgs sign in page > but it errors with AADSTS50011: The URL specified in the request  does not match the reply URLs configured for the application

should this work with all Gov clouds GCC, GCCH, DOD ?

**Comment by jasoth** [comment]
I have not tested the command when connecting to the USGov cloud but the error you are getting does not sound related.
You did not specify a RedirectUri in the commend so MSAL defaults to `https://login.microsoftonline.com/common/oauth2/nativeclient`. You need to ensure that url is configured as a Redirect URI on the application object in AAD with ClientId XXXXXX.
![image](https://user-images.githubusercontent.com/17210677/104660208-23c20b00-5694-11eb-9a83-223ec4ad0b8a.png)
