### ISSUE TITLE
System/User Managed Assigned Service Identity Support?

### ISSUE THREAD

**Issue by JustinGrote** [AzureAD/MSAL.PS#24]
I notice this does not have support for Managed Service Identity Scenarios, most common one being Azure Functions with MSI or user-assigned identity support. Is there a particular reason?

If not I can prepare a PR that integrates basically this flow:
```powershell
function Get-AzMSIAccessToken {
    param (
        $Uri = 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F'
    )
    (Invoke-RestMethod  -Headers @{Metadata='true'} -UseBasicParsing -Uri $uri).access_token
}
```

**Comment by jasoth** [comment]
Hi @JustinGrote,
The Managed Service Identity flow shown cannot be accomplished using the MSAL library today and since this module is specific to the MSAL library, it would not be a good candidate for this module. However, it would definitely be a handy snippet or helper function in another module.
