### ISSUE TITLE
Add a timeout to the Get-MsalToken function

### ISSUE THREAD

**Issue by danstis** [AzureAD/MSAL.PS#6]
As a user of the module, 
I would like a timeout to be added to the Get-MsalToken function, 
so that when token generation fails, or the user closes the browser the function times out after a predetermined interval.

I imagine this timeout should default to 2 minutes, or something similar.

**Comment by jasoth** [comment]
I agree. This is a problem when using the system browser which is the only option for PowerShell Core at the moment. Time permitting, I will think about how to best resolve this. Feel free to submit a pull request if you can get it working better.
