### ISSUE TITLE
-Scope or -Scopes?

### ISSUE THREAD

**Issue by slarionoff** [AzureAD/MSAL.PS#60]
Hi there! When I ran a help for a "Get-MsalToken" command it returned me a contradictory information:

```
help Get-MsalToken
...
SYNTAX
    Get-MsalToken ... [-Scopes <String[]>] 
...
    -------------------------- EXAMPLE 1 --------------------------

    PS C:\>Get-MsalToken -ClientId '00000000-0000-0000-0000-000000000000' -Scope 'https://graph.microsoft.com/User.Read','https://graph.microsoft.com/Files.ReadWrite'
```

Everywhere in a description there's "-Scopes", in all examples it is "-Scope".

I guess you provide this man page together with a code, right? Then it is to be corrected. Thank you!

**Comment by jasoth** [comment]
Thanks for pointing this out. I have made the update here in the repo but it will not show up until another version gets published to PowerShell Gallery.
