### ISSUE TITLE
Primary refresh token missing in WebView2, unable to authenticate

### ISSUE THREAD

**Issue by Snaddr** [AzureAD/MSAL.PS#75]
I have an enterprise app reg in Azure that is used as authentication to another enterprise app reg that exposes an API. I have been using MSAL.PS with Windows PowerShell 5.1 for a long time as a means of reaching this API directly from PowerShell, which works flawlessly (even with SSO). This produces the following WebView, which allows me to one-click sign-in;
![image](https://github.com/AzureAD/MSAL.PS/assets/52966687/1ac331a6-6994-47fe-a7b3-ebe33c7fbd7a)

If I try the exact same flow in PowerShell Core (any version), the primary refresh token seems to be completely missing inside Edge's WebView2, as it shows the Device State is "unregistered" and I have to manually type in my details. 
![image](https://github.com/AzureAD/MSAL.PS/assets/52966687/001b0f91-5752-4c87-b9e8-c11eaab7be94)
Because the PRT is somehow missing, typing in your credentials manually is not gonna get you anywhere. Our conditional access policies require an AAD managed device, which blocks me from signing in as the request thinks my device is "unregistered" (hence why I think the PRT is missing). dsregcmd /status shows that my AzureAdPrt is fine.
![image](https://github.com/AzureAD/MSAL.PS/assets/52966687/6e988aab-3465-4729-a4ae-d44be2f051c3)

I'm definately in over my head with this one, any feedback and/or attempts to help is greatly appreciated!

**Comment by bgavrilMS** [comment]
This is a bug in MSAL, where we shouldn't be using WebView2 because it cannot get SSO with Windows and cannot prove that the device is managed by your organization. We were not able to fix this issue, so we had MSAL use to Webview1 when talking to AAD.

**Comment by bgavrilMS** [comment]
@Snaddr - I agree that using another module is the best path forward, but I would suggest that you use - https://learn.microsoft.com/en-us/powershell/microsoftgraph/get-started?view=graph-powershell-1.0 - mainly because it's officially supported by Microsoft and signed by Microsoft.

**Comment by rvdwegen** [comment]
For anyone running into this, you can also set UseEmbeddedWebView to false, it'll open a browser window instead of a popup.
Unfortunately it does mean you'll have to reauth on every token request.
I'm still on the lookout for a solution for that last part, be it using this module or a different solution.
