### ISSUE TITLE
MSAL.PS 4.14.0.1 and X5C

### ISSUE THREAD

**Issue by abatishchev** [AzureAD/MSAL.PS#8]
I looked at [the source code](https://www.powershellgallery.com/packages/MSAL.PS/4.14.0.1/Content/Get-MsalToken.ps1) of MSAL.PS version 4.14.0.1 and searched for "x5c". I see all occurrences have been commented:

```powershell
#
# [Parameter(Mandatory=$true, ParameterSetName='ConfidentialClientCertificate')]
# [Parameter(Mandatory=$true, ParameterSetName='ConfidentialClientCertificate-AuthorizationCode')]
# [Parameter(Mandatory=$true, ParameterSetName='ConfidentialClientCertificate-OnBehalfOf')]
# [switch] $SendX5C,

#if ($SendX5C) { [void] $AquireTokenParameters.WithSendX5C($SendX5C) }
```

Why? Is there a (pre-release) version where it's not/

**Comment by abatishchev** [comment]
Here's [the commit](https://github.com/jasoth/MSAL.PS/commit/d4297bcf3d93c65d5a3c34e083f7acb1abdd1cf3) where it was added as commented from the start.

@jasoth, can you please commented why?

**Comment by jasoth** [comment]
I was going to implement it but have not had time to figure out how to implement properly and test.

Jason Thompson
Sr. Program Manager<https://aka.ms/jasoth/LinkedIn> | Microsoft Identity CxP GTP<https://azure.microsoft.com/en-us/case-studies/?service=active-directory> | +1 (513) 826-9258<tel:+15138269258>
Microsoft Teams (Chat)<sip:jasoth@microsoft.com> | Book meeting<https://aka.ms/jasoth/bookmeeting> | Calendar availability (EST/EDT)<https://aka.ms/jasoth/calendar>

**Comment by abatishchev** [comment]
Would be great to have this feature as right now the latest version doesn't work with 1PA.

Do you know if there any alternative to get it working from PowerShell?

**Comment by jasoth** [comment]
I would suggest using New-MsalClientApplication and then use the WithSendX5C method<https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.acquiretokenforclientparameterbuilder.withsendx5c?view=azure-dotnet> on the application object from PowerShell to do X5C.

Jason Thompson
Sr. Program Manager<https://aka.ms/jasoth/LinkedIn> | Microsoft Identity CxP GTP<https://azure.microsoft.com/en-us/case-studies/?service=active-directory> | +1 (513) 826-9258<tel:+15138269258>
Microsoft Teams (Chat)<sip:jasoth@microsoft.com> | Book meeting<https://aka.ms/jasoth/bookmeeting> | Calendar availability (EST/EDT)<https://aka.ms/jasoth/calendar>

**Comment by abatishchev** [comment]
Here's what appears to work for me:

```powershell
if ($SendX5C)
{
    $app = New-MsalClientApplication -ClientId $clientId -TenantId $tenantId -Authority $authority -ClientCertificate $cert
    $scopes = [string[]] @( $Scope )
    $response = $app.AcquireTokenForClient($scopes).WithSendX5C($true).ExecuteAsync().GetAwaiter().GetResult()
}
else
{
    $response = Get-MsalToken -ClientId $clientId -TenantId $tenantId -Authority $authority -Scopes $Scope -ClientCertificate $cert
}
```

Still would be great if it could be just a switch on `Get-MsalToken`. Thanks!

**Comment by jasoth** [comment]
I added the SendX5C parameter in the latest update.

**Comment by abatishchev** [comment]
@jasoth I'm having a problem with parameters set too. From the list for version `4.16.0.2` I see that I can include `SendX5C` only in one of them:

```powershell
Get-MsalToken [-SendX5C] [-AuthorizationCode <String>] [-UserAssertion <String>] [-UserAssertionType <String>] [-AzureCloudInstance
    {None | AzurePublic | AzureChina | AzureGermany | AzureUsGovernment}] [-TenantId <String>] [-Authority <Uri>]
    [-ConfidentialClientApplication] <IConfidentialClientApplication> [-Scopes <String[]>] [-CorrelationId <Guid>] [-ExtraQueryParameters
    <Hashtable>] [-ForceRefresh] [<CommonParameters>]
```

But I want to call it in the following way:

```powershell
Get-MsalToken -ClientId $c `
              -TenantId $t `
              -Authority https://login.windows-ppe.net/$t/v2.0 `
              -Scopes https://management.core.windows.net/.default `
              -ClientCertificate $cert `
              -SendX5C
```

Can you please add SendX5C to more/rest of parameter sets?

**Comment by jasoth** [comment]
There are two other usages as well. I assigned it to all parameter sets that involve a ClientCertificate. However, the combination of parameters you have there is not resolving correctly for some reason. I'll take a look at some point.

```
    Get-MsalToken [-ClientId] <String> -ClientCertificate <X509Certificate2> [-SendX5C] -UserAssertion <String>
    [-UserAssertionType <String>] [-RedirectUri <Uri>] [-AzureCloudInstance {None | AzurePublic | AzureChina |
    AzureGermany | AzureUsGovernment}] [-TenantId <String>] [-Authority <Uri>] [-Scopes <String[]>] [-CorrelationId
    <Guid>] [-ExtraQueryParameters <Hashtable>] [<CommonParameters>]

    Get-MsalToken [-ClientId] <String> -ClientCertificate <X509Certificate2> [-SendX5C] -AuthorizationCode <String>
    [-RedirectUri <Uri>] [-AzureCloudInstance {None | AzurePublic | AzureChina | AzureGermany | AzureUsGovernment}]
    [-TenantId <String>] [-Authority <Uri>] [-Scopes <String[]>] [-CorrelationId <Guid>] [-ExtraQueryParameters
    <Hashtable>] [<CommonParameters>]

    Get-MsalToken [-SendX5C] [-AuthorizationCode <String>] [-UserAssertion <String>] [-UserAssertionType <String>]
    [-AzureCloudInstance {None | AzurePublic | AzureChina | AzureGermany | AzureUsGovernment}] [-TenantId <String>]
    [-Authority <Uri>] [-ConfidentialClientApplication] <IConfidentialClientApplication> [-Scopes <String[]>]
    [-CorrelationId <Guid>] [-ExtraQueryParameters <Hashtable>] [-ForceRefresh] [<CommonParameters>]
```

**Comment by abatishchev** [comment]
hi, I updated to `4.16.0.4` but still getting an error:

>Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used
     | together or an insufficient number of parameters were provided.

How I ran the script:

>Get-MsalToken -ClientId $clientId -TenantId $tenantId -Authority $authority -Scopes $Scope -ClientCertificate $cert -XendX5C

**Comment by jasoth** [comment]
This should be fixed now.
